<!-- Page d'accueil de l'utilisateur -->

<h1>Bonjour <?= $_SESSION['user']['firstName'] ?></h1>
<div class="container">
    <section class="info">

    </section>
    <section class="message">
        <button class="action">Modifier</button>
    </section>
    <section class="news">
        <ul>
            <li><a href="http://"></a></li>
        </ul>

    </section>
    <section class="topic">

    </section>
</div>
                        